USE PointPay;
GO

DROP TABLE IF EXISTS Returns;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS WalletTransactions;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Wallets;
DROP TABLE IF EXISTS Employees;
GO

USE master;
Drop Database PointPay;
